### ISSUE TITLE
MakePublic() Error with symbols

### ISSUE THREAD

**Issue by TAINCER** [SociallyDev/Spaces-API#32]
When the Key contains a symbol (In my case) like an @ (at) the functions returns an error (Exception).
Is there any workaround or does this needs a fix?

## Code:

````php
<?php
require 'vendor/autoload.php';

$key = "KEY";
$secret = "SECRET";

$space_name = "SPACE_NAME";
$region = "REGION";

$space = new SpacesConnect($key, $secret, $space_name, $region);

$space->MakePublic("@acex/mod.cpp");
````
---

## Exception:

````bash
root@server:~# php setFilesPublic.php
PHP Fatal error:  Uncaught SpacesAPIException: {"error":{"message":null,"code":"SignatureDoesNotMatch","type":"client","http_code":403}} in /root/vendor/sociallydev/spaces-api/spaces.php:510
Stack trace:
#0 /root/vendor/sociallydev/spaces-api/spaces.php(433): SpacesConnect->HandleAWSException(Object(Aws\S3\Exception\S3Exception))
#1 /root/vendor/sociallydev/spaces-api/spaces.php(231): SpacesConnect->PutObjectACL('@acex/mod.cpp', Array)
#2 /root/setFilesPublic.php(12): SpacesConnect->MakePublic('@acex/mod.cpp')
#3 {main}
  thrown in /root/vendor/sociallydev/spaces-api/spaces.php on line 510
````

**Comment by CodeJunkieio** [comment]
@TAINCERcs I did some investigation and digging, I even found some of your bug reports on digitalocean and the aws repo. I've tried a few things with no luck. It appears it's a AWS problem see (https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)
Unfortunately this means that this issue cannot be solved in the library
