### ISSUE TITLE
GetObject Uncaught exception SignatureDoesNotMatch

### ISSUE THREAD

**Issue by fabricioviana** [SociallyDev/Spaces-API#43]
Hello, need some help, please.

 I have a file named "file test.txt".

I can list this file:

```
$files = $space->ListObjects();
print_r($files);

Array
(
    [Key] => file test.txt
    [LastModified] => 1589716222
    [ETag] => "5e4a7b4dc66285e82fdee1847788113f"
    [Size] => 397
    [StorageClass] => STANDARD
    [Owner] => Array
        (
            [DisplayName] => 1790446
            [ID] => 1790446
        )

)
```

But if I do:

```$file_info = $space->GetObject("file test.txt");```

I got this error:

```
Fatal error:  Uncaught exception 'SpacesAPIException' with message '{"error":{"message":null,"code":"SignatureDoesNotMatch","type":"client","http_code":403}}' in /var/www/html/spaces.php:510
Stack trace:
#0 /var/www/html/ccr/spaces.php(210): SpacesConnect->HandleAWSException(Object(Aws\S3\Exception\S3Exception))
#1 /var/www/html/test.php(38): SpacesConnect->GetObject('file test.txt')
#2 {main}
  thrown in /var/www/html/spaces.php on line 510
```

Files containing the # character also gave an error.

Could someone help me, please?

Thank you!

**Comment by SociallyDev** [comment]
Hello, sorry for the super late reply. I've rewritten Spaces-API and the new Spaces-API handles spaces so you can name your objects anything!
Here's an example:
```php
my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//Returns all available data on a file.
$my_space->fileInfo("my file with spacing.txt");
```
