### ISSUE TITLE
Errors when setting CORS

### ISSUE THREAD

**Issue by Daxcor69** [SociallyDev/Spaces-API#45]
The cors I am setting is:
```
$CORS = '
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration>
	<CORSRules>
		<AllowedOrigins>*</AllowedOrigins>
		<AllowedMethods>POST</AllowedMethods>
		<AllowedMethods>GET</AllowedMethods>
	        <AllowedMethods>HEAD</AllowedMethods>
		<AllowedHeaders>*</AllowedHeaders>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
	</CORSRules>
</CORSConfiguration>';
```
I am creating the php array this way:
```
$ob = simplexml_load_string($CORS);
$json = json_encode($ob);
$new_policy = json_decode($json, true);
```

Set the policy this way:

`$space->PutCORS($new_policy);`

The error from the sdk is this:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Found 2 errors while validating the input provided for the PutBucketCors operation:
[CORSConfiguration][CORSRules][0][AllowedMethods] is missing and is a required parameter
[CORSConfiguration][CORSRules][0][AllowedOrigins] is missing and is a required parameter in /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/Api/Validator.php:65
Stack trace:
#0 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/Middleware.php(78): Aws\Api\Validator->validate()
#1 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/S3/S3Client.php(540): Aws\Middleware::Aws\{closure}()
#2 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/S3/S3Client.php(563): Aws\S3\S3Client::Aws\S3\{closure}()
#3 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/S3/S3Client.php(497): Aws\S3\S3Client::Aws\S3\{closure}()
#4 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/S3/S3Client.php(516): Aws\S3\S3Client::Aws\S3\{closure}()
#5 /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/Middleware.php(54): Aws\S3\S3C in /mnt/foundry/cronscripts/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65
```

The output when I echo each stage is:

```
       SimpleXMLElement Object
(
    [CORSConfiguration] => SimpleXMLElement Object
        (
            [CORSRules] => SimpleXMLElement Object
                (
                    [AllowedOrigins] => *
                    [AllowedMethods] => Array
                        (
                            [0] => POST
                            [1] => GET
                            [2] => HEAD
                        )

                    [AllowedHeaders] => *
                    [MaxAgeSeconds] => 3000
                )
        )
)

{"CORSConfiguration":{"CORSRules":{"AllowedOrigins":"*","AllowedMethods":["POST","GET","HEAD"],"AllowedHeaders":"*","MaxAgeSeconds":"3000"}}}

Array
(
    [CORSConfiguration] => Array
        (
            [CORSRules] => Array
                (
                    [AllowedOrigins] => *
                    [AllowedMethods] => Array
                        (
                            [0] => POST
                            [1] => GET
                            [2] => HEAD
                        )
                    [AllowedHeaders] => *
                    [MaxAgeSeconds] => 3000
                )
        )
)```

I am totally stumped at this point.  What I can see is I am missing [0] but I don't really know.  Any help would be appreciated.

**Comment by SociallyDev** [comment]
Sorry for the (Super) late reply. I've been writing the v2. CORS should now work for you with the update. Here's the snippet that should work:

```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");

//This allows all sources to use your file.
$my_space->setCORS([
  [
    "origins" => ["*"],
    "methods" => ["GET", "HEAD", "OPTIONS"]
  ]
]);
```

Check out the new README: https://github.com/SociallyDev/Spaces-API
