### ISSUE TITLE
RejectedPromise.php on line 16

### ISSUE THREAD

**Issue by emineinnovations** [SociallyDev/Spaces-API#65]
**I am getting following error when trying to upload file. Can anyone help me on this?**

```Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\RejectedPromise.php:16 
Stack trace: 
#0 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\RejectedPromise.php(16): method_exists(Array, 'then') #1 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\Aws\Handler\GuzzleV6\GuzzleHandler.php(56): GuzzleHttp\Promise\RejectedPromise->__construct(Array) 
#2 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(203): Aws\Handler\GuzzleV6\GuzzleHandler::Aws\Handler\GuzzleV6\{closure}(Object(GuzzleHttp\Exception\ConnectException)) 
#3 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Object(GuzzleHttp\Exception\ConnectException), Array) 
#4 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() 
#5 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Handler\CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() 
#6 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Handler\CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() 
#7 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) 
#8 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() 
#9 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() 
#10 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() 
#11 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() 
#12 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() 
#13 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() 
#14 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\Aws\S3\S3ClientTrait.php(34): GuzzleHttp\Promise\Promise->wait() 
#15 C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\spaces.php(169): Aws\S3\S3Client->upload('my_space', 'song.lk/capture...', Resource id #113, 'private') 
#16 C:\xampp\htdocs\songdev\private\upload\index.php(94): Space->uploadFile('C:/Users/SHAN/D...', 'song.lk/capture...', 'private') 
#17 {main} thrown in C:\xampp\htdocs\songdev\private\upload\Spaces-API-master\aws\GuzzleHttp\Promise\RejectedPromise.php on line 16```

**Comment by MacroMan** [comment]
I have been unable to replicate this issue.

Can you provide any more information?

**Comment by MacroMan** [comment]
New major version release, so not fixing.
